# Generated by Django 5.1.4 on 2025-01-10 11:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_characters'),
    ]

    operations = [
        migrations.CreateModel(
            name='House',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TimeField()),
            ],
        ),
        migrations.AddField(
            model_name='characters',
            name='creaeted',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='characters',
            name='house',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='app.house', verbose_name="Character's house"),
            preserve_default=False,
        ),
    ]
